### ISSUE TITLE
RR1 should handle large and very large blocks differently

### ISSUE THREAD

**Issue by sjain12** [mogproject/cricca#2]
There is a bug in the implementation of RR1. According to the theory, there are 2 cases depending on the size of a block, and these need to be handled separately. 

Case 1: if len(block) > 2**k, do what Madi's code was doing: let u and v be two vertices in the block then set A[v,v] = A[u,v], retain v, and delete the rest of the vertices in the block (including u). 

Case 2: If k < len(block) <= 2**k, retain k vertices (not just 1 representative vertex) and delete the rest of the vertices in the block. No need to modify the vertex weights in this case. 

The current code is applying the rules of case 1 to case 1 as well as case 2.

**Comment by mogproject** [comment]
Suggestion by @sjain12 

```
def remove_arbitrary(A, blocks, k):
    ‘’'
    Args: A : 2-D pandas adjacency list
    ‘’'
    # reduction rule 2
    toremove = []
    b_index=0
    for block in blocks:
        if len(block) > 2**k:
            v = block.pop()
            u = block.pop()
            A.loc[v,v] = A.loc[u,v]
            toremove.append(u)
            for i in block:
                toremove.append(i)
            # replace block w. block containing representative vertex
            newblock = set()
            newblock.add(v)
            blocks[b_index]=newblock
        elif len(block) > k:
            count = 0
            newblock = set()
            for i in block:
                count = count + 1
                if count > k:
                    toremove.append(i)
                else:
                    newblock.add(i)
            blocks[b_index]=newblock
        b_index+=1
    A_red = A.drop(toremove, axis=1)
    A_red = A_red.drop(toremove, axis=0)
```

**Comment by mogproject** [comment]
@sjain12 Do you have an example where the current implementation goes wrong?

**Comment by mogproject** [comment]
The current implementation should be fine.
